### PR TITLE
changed a few thing to run smoothly under cygwin

### PR DESCRIPTION
**Pull request by riedel**
I tried this great script under cygwin, ran in a few issues and fixed them quickly. Tested it in git bash. Seems to still work as expected.

* set enviroment
* get realpath to backend a bit more reliably under bash (when $0 is in path)
* umask to hide a bit better towards other users (still not perfect and elevation can be easily highjacked by at least the same user)
* moved help dialog for already elevated users

### CODE REVIEW

**Review by RicardoRdzG — APPROVED** [review]
It looks great, that should fix issue 11 too, just would add some comments for future contributors

**Comment by purplesyringa** [comment]
Sorry for inactivity. Looks like this pr has some conflicts - can you please resolve them?

**Comment by riedel** [comment]
I merged and did a minor improvement

Quoting from the bash manual :
> The  command  substitution  $(cat  file)  can be replaced by the equivalent but faster $(< file).

**Comment by purplesyringa** [comment]
Thank you!

**Pull request merged**
