### PR TITLE
Get bash path

### PR DESCRIPTION
**Pull request by gucong3000**
bash_path="$(cygpath -w /bin/sh)"

### CODE REVIEW

**Comment by purplesyringa** [comment]
Please use `cygpath -W` instead of `cygpath -w` because only `-W` works on my machine.

Anyways, that you for this PR! Never knew about such command.

**Comment by gucong3000** [comment]
> Please use cygpath -W

Looks like it not work for me.
 
```shell
cdyf@qil  /e/work/git-bash-shell (lxss)
$ cygpath -W /bin/sh
Usage: cygpath (-d|-m|-u|-w|-t TYPE) [-f FILE] [OPTION]... NAME...
       cygpath [-c HANDLE]
       cygpath [-ADHOPSW]
       cygpath [-F ID]

Convert Unix and Windows format paths, or output system path information

Output type options:

  -d, --dos             print DOS (short) form of NAMEs (C:\PROGRA~1\)
  -m, --mixed           like --windows, but with regular slashes (C:/WINNT)
  -M, --mode            report on mode of file (binmode or textmode)
  -u, --unix            (default) print Unix form of NAMEs (/cygdrive/c/winnt)
  -w, --windows         print Windows form of NAMEs (C:\WINNT)
  -t, --type TYPE       print TYPE form: 'dos', 'mixed', 'unix', or 'windows'

Path conversion options:

  -a, --absolute        output absolute path
  -l, --long-name       print Windows long form of NAMEs (with -w, -m only)
  -p, --path            NAME is a PATH list (i.e., '/bin:/usr/bin')
  -U, --proc-cygdrive   Emit /proc/cygdrive path instead of cygdrive prefix
                        when converting Windows path to UNIX path.
  -s, --short-name      print DOS (short) form of NAMEs (with -w, -m only)
  -C, --codepage CP     print DOS, Windows, or mixed pathname in Windows
                        codepage CP.  CP can be a numeric codepage identifier,
                        or one of the reserved words ANSI, OEM, or UTF8.
                        If this option is missing, cygpath defaults to the
                        character set defined by the current locale.

System information:

  -A, --allusers        use `All Users' instead of current user for -D, -O, -P
  -D, --desktop         output `Desktop' directory and exit
  -H, --homeroot        output `Profiles' directory (home root) and exit
  -O, --mydocs          output `My Documents' directory and exit
  -P, --smprograms      output Start Menu `Programs' directory and exit
  -S, --sysdir          output system directory and exit
  -W, --windir          output `Windows' directory and exit
  -F, --folder ID       output special folder with numeric ID and exit
Try `cygpath --help' for more information.
cdyf@qil  /e/work/git-bash-shell (lxss)

$ cygpath -w "/bin/sh"
C:\Program Files\Git\usr\bin\sh.exe

cdyf@qil  /e/work/git-bash-shell (lxss)
$ git --version
git version 2.16.2.windows.1
```

**Comment by purplesyringa** [comment]
Hm... It works now for me. I think I tried `cygpath -w`, not `cygpath -w /`.

**Comment by purplesyringa** [comment]
Reverted. `$SHELL` is `/usr/bin/bash`, however, the correct path is `/bin/bash`.

**Pull request merged**
