### PR TITLE
Windows Terminal workaround by using fifos instead of console device

### PR DESCRIPTION
**Pull request by riedel**
aims to workaround  #36

### CODE REVIEW

**Comment by riedel** [comment]
There is actually a small bug fixed here https://github.com/imachug/win-sudo/pull/49/commits/c6ac43413c99a0becb0593795b9afd30ac23619a#diff-1fa39d56a58df8d32ee980b4cf0927bc11ac1dd009d7a333080d0844476d4098R103

it does assume fifo mode for all fds at once (no clue why you would want otherwise). The grep line might not be too smart. Maybe there is a better way to detect a windows console device.

I tested cygwin on the windows console. Probably msys2 needs testing.

**Comment by purplesyringa** [comment]
I'm honestly no longer really involved with the project, as I don't use Windows often anymore, so I can't really test msys2 at the moment. If you do that for me, I will gladly merge the PR.

**Comment by riedel** [comment]
checked that it works for me eg. on standard bash for windows (msys) and with the legacy and new windows console as well as mintty. Only mintty actually manages to share the tty with the elevated backend for some reason (this is what the patch addresses)

**Comment by purplesyringa** [comment]
Thank you for your PR!

**Pull request merged**
