### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by essexgit**
Seemed to be an out of date url / github repo in the filepath

### CODE REVIEW

**Comment by purplesyringa** [comment]
Yeah, thank you! Could you please fix formatting though, removing the space and the empty line? (or was done intentionally?)

**Comment by purplesyringa** [comment]
Also, can you please change the username in install.sh too?

**Comment by essexgit** [comment]
> 

Hi - I removed the unintentional space and newline

**Comment by essexgit** [comment]
> 

I've updated the username in the install.sh - I haven't checked/tested though - it didn't cause a problem.
Thanks

**Comment by purplesyringa** [comment]
Thank you!

**Comment by essexgit** [comment]
You're welcome, my pleasure

**Pull request merged**
