### PR TITLE
Enhancement/better install script

### PR DESCRIPTION
**Pull request by DemianTinkiel**
* made script file so it can be executed in single command
* script doesn't fail if installed before

### CODE REVIEW

**Comment by DemianTinkiel** [comment]
@imachug a small suggestion to make it easier to install

**Comment by purplesyringa** [comment]
> curl -s https://raw.githubusercontent.com/imachug/win-sudo/betterInstallScript/install.sh | sh

I guess I should replace `betterInstallScript` with `master` after merge, right?

**Comment by DemianTinkiel** [comment]
Sorry I thought I did the branch part too. Yes just open the sh as raw in github and copy the url

**Comment by purplesyringa** [comment]
Done now :)

**Pull request merged**
